# Generated by Django 4.2 on 2023-09-16 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrierMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('carrier', models.CharField(max_length=255)),
                ('mon_server', models.CharField(db_index=True, max_length=255)),
                ('last_check', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('alert', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CarrierMonUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('hp_org_id', models.CharField(max_length=20)),
                ('device_id', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=30)),
                ('carrier_monitoring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='carrier_monitoring.carriermonitoring')),
                ('hpbx_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.hpbxserver')),
            ],
            options={
                'unique_together': {('carrier_monitoring', 'user_name')},
            },
        ),
    ]
