# Generated by Django 4.2 on 2023-09-17 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrier_monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carriermonuser',
            name='carrier_monitoring',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='carrier_monitoring.carriermonitoring'),
        ),
    ]
