# Generated by Django 4.2 on 2023-09-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HPBXServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=255)),
                ('api_fqdn', models.CharField(max_length=255)),
                ('calls_fqdn', models.CharField(max_length=255)),
            ],
        ),
    ]
